#!/bin/bash
CERTBOT_CMD="/opt/certbot/certbot-auto"
RENEW_BEFORE_DAYS=30

VALID_DAYS="$($CERTBOT_CMD certificates 2>/dev/null |grep -Eo "VALID: [0-9]+ days" |awk '{print $2}' |sort -n|head -n 1)"

if [ $VALID_DAYS -le $RENEW_BEFORE_DAYS ]
then
  echo "============================"
  echo " VALID: ${VALID_DAYS} days"
  echo " Renewing certifcates"
  echo "============================"
  $CERTBOT_CMD renew -n

  echo "============================"
  echo " Restarting web server"
  echo "============================"
  systemctl restart optnginx
fi
